<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block Magebit\Learning\Block\AttributeElement
 * @var $_helper Magento\Catalog\Helper\Output
 * @var $_product \Magento\Catalog\Api\Data\ProductInterface
 */
?>
<?php
    $attributes = $block->getAttributes();
    $shortDescription = $block->getShortDescription();
?>

<?php if(!empty($attributes) && !empty($shortDescription)): ?>
    <div class="attribute-element">
        <?php if(!empty($attributes)): ?>
            <ul>
                <?php foreach ($attributes as $attribute): ?>
                    <li><strong><?= $attribute["label"] ?></strong>: <?= $attribute['value'] ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?php if($shortDescription): ?>
            <?= $shortDescription ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
